version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: keycloak-db
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
    command:
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
